"vim-plug
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'ctrlpvim/ctrlp.vim'
Plug 'tpope/vim-fugitive'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'itchyny/lightline.vim'
Plug 'dracula/vim'
Plug 'sickill/vim-monokai'
call plug#end()

syntax enable
filetype plugin indent on

set number
set ignorecase " case insensitive search
set smartcase
set nohlsearch " don't highlight search results
set ruler " show line number and cursor position
set showcmd " display incomplete commands at bottom
set wildmenu " shows autocomplete menu
set showmode " shows editing mode

" indentation settings
set autoindent
set shiftwidth=2
set expandtab

" status line settings
set laststatus=2 " always show status line

set background=dark
set t_Co=256
colorscheme dracula
