# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [ -f ~/.bashrc-orig ]; then
	. ~/.bashrc-orig
fi

# User specific aliases and functions

# File Redirection will not overwrite existing files
set -o noclobber

alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias gdb='gdb -q'
alias grep='grep --color'
# force tmux to assume terminal supports 256 colors
alias tmux='tmux -2'

export EDITOR='vim'

export PS1='\[\033[01;33m\]--\h \w \$\[\033[00m\] '
