"vim-plug
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'ctrlpvim/ctrlp.vim'
Plug 'tpope/vim-fugitive'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'garbas/vim-snipmate'
Plug 'honza/vim-snippets'
Plug 'itchyny/lightline.vim'
Plug 'sickill/vim-monokai'
Plug 'altercation/vim-colors-solarized'
Plug 'Vimjas/vim-python-pep8-indent'
Plug 'morhetz/gruvbox'
call plug#end()

" use vim settings rather than vi settings
set backspace=2
"set nocompatible              " be iMproved, required
syntax enable
filetype plugin indent on

set ignorecase " case insensitive search
set smartcase
set nohlsearch " don't highlight search results
set ruler " show line number and cursor position
set showcmd " display incomplete commands at bottom
set wildmenu " shows autocomplete menu
set showmode " shows editing mode

" indentation settings
set autoindent
set shiftwidth=2
set expandtab
set tabstop=2
set textwidth=79
" v 7.3 onwards
if exists('+colorcolumn')
  set colorcolumn=80
else
  " highlight from 80th
  "au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>79v.\+', -1)
  " highlight only 80th column
  " 2mat ErrorMsg '\%80v.'
  au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%80v', -1)
endif

" status line settings
set laststatus=2 " always show status line

set background=dark
set t_Co=256
let g:solarized_termcolors=256
colorscheme gruvbox

" ctrlp options
" search from cwd
let g:ctrlp_working_path_mode = 'a'
" exclude from search
set wildignore+=*.o,*.so,*.a,*.pyc,*/.git/*,tags

au Filetype python setlocal shiftwidth=2 tabstop=2

au FileType markdown setlocal syntax=OFF
